workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: 3.24.3
    triggering:
      events:
        - push
    scripts:
      - name: Accept Android licenses
        script: |
          yes | flutter doctor --android-licenses
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter clean
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing: {}
